### ISSUE TITLE
Error connecting: (localhost:18872) failed to connect: [Errno 111] Connection refused, attempt 0

### ISSUE THREAD

**Issue by iamycee** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#28] opened 2020-01-10 10:02 UTC
When I run the starter code for chapter 8, I get the following error: 
`Error connecting: (localhost:18872) failed to connect: [Errno 111] Connection refused, attempt 0`

How do I fix this? I'm on CARLA version 0.9.6

**Comment by praveen-palanisamy** [comment] 2020-01-12 01:34
Hi @iamycee , 
For CARLA 0.9.x, use the code in this repository: [https://github.com/praveen-palanisamy/macad-gym](https://github.com/praveen-palanisamy/macad-gym). 
I am closing this as it is a duplicate of #27

**Closed by praveen-palanisamy** 2020-01-12 01:34 UTC
